namespace Test.Shared.Suites
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Reflection;
    using System.Text.Json;
    using System.Threading.Tasks;
    using Pneuma.Chunking.Chunking;
    using Pneuma.Chunking.Enums;
    using Pneuma.Chunking.Models;
    using Pneuma.Chunking.Tokenization;
    using Touchstone.Core;

    /// <summary>
    /// Exact-parity gate for the ported chunking library. The embedded golden fixture
    /// (Fixtures/chunking-parity.json) was generated by running Partio's own chunkers over a fixed corpus
    /// with SharpToken cl100k_base 2.0.6. This suite runs the identical corpus through Pneuma.Chunking and
    /// asserts byte-identical chunk boundaries, proving the port reproduces Partio's output exactly.
    /// </summary>
    public static class ChunkingParitySuite
    {
        private const string _ResourceName = "Test.Shared.Fixtures.chunking-parity.json";

        /// <summary>Build the suite.</summary>
        /// <returns>Suite descriptor.</returns>
        public static TestSuiteDescriptor Build()
        {
            return new TestSuiteDescriptor(
                suiteId: "ChunkingParity",
                displayName: "Chunking Partio Parity",
                cases: new List<TestCaseDescriptor>
                {
                    new TestCaseDescriptor("ChunkingParity", "ChunkBoundariesMatchPartioGolden", "Pneuma.Chunking reproduces Partio's chunk boundaries byte-for-byte across the golden corpus",
                        executeAsync: ct =>
                        {
                            List<GoldenCase> cases = LoadGolden();
                            if (cases.Count == 0) throw new Exception("golden fixture was empty");

                            ITokenizerAdapter tokenizer = new SharpTokenTokenizerAdapter("cl100k_base");
                            foreach (GoldenCase golden in cases)
                            {
                                List<string> actual = Chunk(golden, tokenizer);
                                if (actual.Count != golden.Chunks.Count)
                                    throw new Exception("parity mismatch [" + golden.CorpusId + "/" + golden.Strategy + "/max=" + golden.MaxTokens + "/ov=" + golden.Overlap + "]: chunk count " + actual.Count + " != golden " + golden.Chunks.Count);
                                for (int i = 0; i < actual.Count; i++)
                                {
                                    if (!String.Equals(actual[i], golden.Chunks[i], StringComparison.Ordinal))
                                        throw new Exception("parity mismatch [" + golden.CorpusId + "/" + golden.Strategy + "/max=" + golden.MaxTokens + "/ov=" + golden.Overlap + "] chunk " + i + " differs from Partio golden");
                                }
                            }

                            return Task.CompletedTask;
                        })
                });
        }

        private static List<string> Chunk(GoldenCase golden, ITokenizerAdapter tokenizer)
        {
            ChunkStrategyEnum strategy = MapStrategy(golden.Strategy);
            ChunkingConfiguration config = new ChunkingConfiguration
            {
                Strategy = strategy,
                FixedTokenCount = golden.MaxTokens,
                OverlapCount = golden.Overlap
            };

            if (strategy == ChunkStrategyEnum.SentenceBased) return SentenceChunker.Chunk(golden.Text, config, tokenizer, golden.MaxTokens);
            if (strategy == ChunkStrategyEnum.ParagraphBased) return ParagraphChunker.Chunk(golden.Text, config, tokenizer, golden.MaxTokens);
            return FixedTokenChunker.Chunk(golden.Text, config, tokenizer, golden.MaxTokens);
        }

        private static ChunkStrategyEnum MapStrategy(string strategy)
        {
            if (String.Equals(strategy, "SentenceBased", StringComparison.OrdinalIgnoreCase)) return ChunkStrategyEnum.SentenceBased;
            if (String.Equals(strategy, "ParagraphBased", StringComparison.OrdinalIgnoreCase)) return ChunkStrategyEnum.ParagraphBased;
            return ChunkStrategyEnum.FixedTokenCount;
        }

        private static List<GoldenCase> LoadGolden()
        {
            Assembly assembly = typeof(ChunkingParitySuite).Assembly;
            using (Stream? stream = assembly.GetManifestResourceStream(_ResourceName))
            {
                if (stream == null) throw new Exception("embedded golden fixture not found: " + _ResourceName);
                using (StreamReader reader = new StreamReader(stream))
                {
                    string json = reader.ReadToEnd();
                    JsonSerializerOptions options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
                    List<GoldenCase>? cases = JsonSerializer.Deserialize<List<GoldenCase>>(json, options);
                    return cases ?? new List<GoldenCase>();
                }
            }
        }

        /// <summary>One golden chunking case captured from Partio.</summary>
        private class GoldenCase
        {
            public string CorpusId { get; set; } = String.Empty;
            public string Text { get; set; } = String.Empty;
            public string Strategy { get; set; } = String.Empty;
            public int MaxTokens { get; set; } = 0;
            public int Overlap { get; set; } = 0;
            public List<string> Chunks { get; set; } = new List<string>();
        }
    }
}
